version: "3.3"
services:
  selv-dhis2-integration:
    image: openlmismz/selv-dhis2-integration
    links:
      - db
      - log
    ports:
      - "8080"
    env_file: .env
  db:
    image: openlmis/postgres:12-debezium
    env_file: .env
  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/selv-dhis2-integration:/var/log'
