version: "3.3"
services:
  dhis2-integration:
    image: openlmis/dev:6
    ports:
      - "5005:5005"
      - "8080:8080"
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
    env_file: .env
  db:
    ports:
      - "5432"
volumes:
  gradlecache:
    external: false
