version: "3.3"
services:
  builder:
    image: openlmis/dev:6
    links:
      - db
      - log
    volumes:
      - '.:/app'
      - '../logback.xml:/logback.xml'
    command:
      - './build.sh'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
      JAVA_OPTS: '-Dlogging.config=/logback.xml'
    env_file: .env
  sonar:
    image: openlmis/dev:6
    links:
      - db
      - log
    volumes:
      - '.:/app'
    entrypoint:
      - 'gradle'
    command:
      - 'sonarqube'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    env_file: .env
  image:
    build: .
    image: openlmismz/selv-v3-dhis2-integration
  db:
    image: openlmis/postgres:12-debezium
    env_file: .env
  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/selv-v3-dhis2-integration:/var/log'
